import type { Book, Category, User } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImageUrl = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  return image ? image.imageUrl : 'https://picsum.photos/seed/default/600/800';
}
const getImageHint = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  return image ? image.imageHint : 'book cover';
}

const samplePdfUrl = 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf';

export const categories: Category[] = [
    { id: 'cs', name: 'Computer Science' },
    { id: 'math', name: 'Mathematics' },
    { id: 'physics', name: 'Physics' },
    { id: 'chem', name: 'Chemistry' },
    { id: 'lit', name: 'Literature' },
    { id: 'history', name: 'History' },
    { id: 'business', name: 'Business' },
    { id: 'medicine', name: 'Medicine' },
];

export const books: Book[] = [
  {
    id: 'pride-and-prejudice',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    publicationYear: 1813,
    category: categories[4],
    subject: 'Romance',
    language: 'English',
    academicLevel: 'High School',
    description: 'A timeless classic exploring themes of love, class, and personal growth in 19th century England.',
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxtaWxrJTIwYW5kJTIwaG9uZXl8ZW58MHx8fHwxNzY4MTEzMjY5fDA&ixlib=rb-4.0.3&q=80&w=1080',
    imageHint: 'milk honey',
    fileUrl: samplePdfUrl,
    pages: 432,
    downloads: 313,
    fileSize: '12.5 MB',
    isFeatured: true,
  },
  {
    id: '3',
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    publicationYear: 2022,
    category: categories[0],
    subject: 'Programming Languages',
    language: 'English',
    academicLevel: 'Graduate',
    description: 'A classic computer science textbook that teaches fundamental principles of programming, including recursion, abstraction, modularity, and programming language design and implementation.',
    coverImage: getImageUrl('book-cover-3'),
    imageHint: getImageHint('book-cover-3'),
    fileUrl: samplePdfUrl,
    pages: 1312,
    downloads: 1204,
    fileSize: '30.2 MB',
    isFeatured: false,
  },
  {
    id: '7',
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    publicationYear: 2021,
    category: categories[0],
    subject: 'Artificial Intelligence',
    language: 'English',
    academicLevel: 'Undergraduate',
    description: 'The leading textbook in Artificial Intelligence. It is used in over 1,500 universities in 135 countries. It is considered the standard text in the field.',
    coverImage: getImageUrl('book-cover-7'),
    imageHint: getImageHint('book-cover-7'),
    fileUrl: samplePdfUrl,
    pages: 464,
    downloads: 987,
    fileSize: '5.8 MB',
    isFeatured: true,
  },
  {
    id: '1',
    title: 'Dune',
    author: 'Frank Herbert',
    publicationYear: 1965,
    category: categories[4],
    subject: 'Political Ecology',
    language: 'English',
    academicLevel: 'Undergraduate',
    description: 'A mythic and emotionally charged hero\'s journey, "Dune" tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, who must travel to the most dangerous planet in theuniverse to ensure the future of his family and his people.',
    coverImage: getImageUrl('book-cover-1'),
    imageHint: getImageHint('book-cover-1'),
    fileUrl: samplePdfUrl,
    pages: 412,
    downloads: 543,
    fileSize: '2.3 MB',
    isFeatured: false,
  },
  {
    id: '2',
    title: 'A People\'s History of the United States',
    author: 'Howard Zinn',
    publicationYear: 1980,
    category: categories[5],
    subject: 'American History',
    language: 'English',
    academicLevel: 'Graduate',
    description: 'A comprehensive history of the United States from the perspective of and for the common people, including Native Americans, slaves, and laborers.',
    coverImage: getImageUrl('book-cover-2'),
    imageHint: getImageHint('book-cover-2'),
    fileUrl: samplePdfUrl,
    pages: 729,
    downloads: 876,
    fileSize: '4.1 MB',
    isFeatured: false,
  },
  {
    id: '4',
    title: 'A Wizard of Earthsea',
    author: 'Ursula K. Le Guin',
    publicationYear: 1968,
    category: categories[4],
    subject: 'Coming of Age',
    language: 'English',
    academicLevel: 'High School',
    description: 'The first book in the Earthsea series, it follows a young wizard named Ged as he attends a school of wizardry and grapples with a shadow beast he accidentally unleashes.',
    coverImage: getImageUrl('book-cover-4'),
    imageHint: getImageHint('book-cover-4'),
    fileUrl: samplePdfUrl,
    pages: 205,
    downloads: 450,
    fileSize: '1.5 MB',
    isFeatured: true,
  },
  {
    id: '5',
    title: 'Critique of Pure Reason',
    author: 'Immanuel Kant',
    publicationYear: 1781,
    category: categories[4],
    subject: 'Metaphysics',
    language: 'German',
    academicLevel: 'Postgraduate',
    description: 'One of the most influential works in the history of philosophy. In it, Kant seeks to determine the limits and scope of metaphysics.',
    coverImage: getImageUrl('book-cover-5'),
    imageHint: getImageHint('book-cover-5'),
    fileUrl: samplePdfUrl,
    pages: 550,
    downloads: 120,
    fileSize: '3.9 MB',
    isFeatured: false,
  },
  {
    id: '6',
    title: 'One Hundred Years of Solitude',
    author: 'Gabriel García Márquez',
    publicationYear: 1967,
    category: categories[4],
    subject: 'Magical Realism',
    language: 'Spanish',
    academicLevel: 'Undergraduate',
    description: 'The multi-generational story of the Buendía family, whose patriarch, José Arcadio Buendía, founds the town of Macondo, the metaphoric Colombia.',
    coverImage: getImageUrl('book-cover-6'),
    imageHint: getImageHint('book-cover-6'),
    fileUrl: samplePdfUrl,
    pages: 417,
    downloads: 788,
    fileSize: '2.1 MB',
    isFeatured: true,
  },
  {
    id: '8',
    title: 'The Power Broker',
    author: 'Robert A. Caro',
    publicationYear: 1974,
    category: categories[5],
    subject: 'Biography',
    language: 'English',
    academicLevel: 'Graduate',
    description: 'A biography of Robert Moses, the "master builder" of mid-20th century New York City, Long Island, Rockland County, and Westchester County, in New York.',
    coverImage: getImageUrl('book-cover-8'),
    imageHint: getImageHint('book-cover-8'),
    fileUrl: samplePdfUrl,
    pages: 1336,
    downloads: 650,
    fileSize: '15.2 MB',
    isFeatured: false,
  }
];

export const users: User[] = [
    { id: 'user-1', name: 'Alice Johnson', email: 'alice@example.com', role: 'admin', memberSince: '2023-01-15' },
    { id: 'user-2', name: 'Bob Williams', email: 'bob@example.com', role: 'member', memberSince: '2023-03-22' },
    { id: 'user-3', name: 'Charlie Brown', email: 'charlie@example.com', role: 'member', memberSince: '2023-05-30' },
    { id: 'user-4', name: 'Diana Prince', email: 'diana@example.com', role: 'member', memberSince: '2023-08-11' },
];
